cinema:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    database: ${MYSQL_DATABASE:cinema_ticketing}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  alioss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIYUN_BUCKET_NAME:}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:1}
