server:
  port: 8084

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${cinema.datasource.driver-class-name}
      url: jdbc:mysql://${cinema.datasource.host}:${cinema.datasource.port}/${cinema.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${cinema.datasource.username}
      password: ${cinema.datasource.password}
  redis:
    host: ${cinema.redis.host}
    port: ${cinema.redis.port}
    password: ${cinema.redis.password}
    database: ${cinema.redis.database}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cinema.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      cinema:
        mapper: debug
        service: info
        controller: info

cinema:
  jwt:
    admin-secret-key: ${JWT_ADMIN_SECRET_KEY:your-admin-secret-key-please-change-me}
    admin-ttl: 72000000000000
    admin-token-name: token
    user-secret-key: ${JWT_USER_SECRET_KEY:your-user-secret-key-please-change-me}
    user-ttl: 72000000000000
    user-token-name: token

  alioss:
    endpoint: ${cinema.alioss.endpoint}
    access-key-id: ${cinema.alioss.access-key-id}
    access-key-secret: ${cinema.alioss.access-key-secret}
    bucket-name: ${cinema.alioss.bucket-name}
